# Generated by Django 2.2.5 on 2020-08-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0004_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaEnc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_faactura', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Encabezado de Factura',
                'verbose_name_plural': 'Encabezados de Factura',
            },
        ),
        migrations.CreateModel(
            name='FacturaDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salidas.FacturaEnc')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Producto')),
            ],
            options={
                'verbose_name': 'Detalles de Factura',
                'verbose_name_plural': 'Detalles de Factura',
            },
        ),
    ]
